# Permalinks
permalink:           pretty

# Setup
title:               Anders Murphy
tagline:             A blog mostly about software development
url:                 https://andersmurphy.com
paginate:            10
baseurl:             ""
google_analytics:    UA-67134330-1
future: false

# Social
github:              https://github.com/andersmurphy
twitter:             https://twitter.com/anders_murphy
linkedin:            https://uk.linkedin.com/pub/anders-murphy/3a/57b/764

# Assets
sass:
  sass_dir:          _sass
  style:            :compressed

# Comments
disqus:
    shortname:      andersmurphy

# Gems
gems:
  - jekyll-sitemap
  - jekyll-paginate

excerpt_separator: <!--more-->
