# Permalinks
permalink:           pretty
relative_permalinks: true

# Setup
title:               Anders Murphy
tagline:             My blog about Android development
url:                 http://andersmurphy.com
paginate:            3
baseurl:             ""
google_analytics:    UA-67134330-1

# Social
github:              https://github.com/andersmurphy
twitter:             https://twitter.com/anders_murphy

# Assets
sass:
  sass_dir:          _sass
  style:            :compressed

# Comments
disqus:
    shortname:      andersmurphy
